title: Tim Krach
description: Software Engineer | Cybersecurity Professional | ソフトウェア／サイバーセキュリティエンジニア
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkrach.github.io" # the base hostname & protocol for your site
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github_username:  tkrach
# Build settings
markdown: kramdown
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "クラックティム"
    url: "/index_jp"
