title: Tim Krach
description: Personal website of Tim Krach
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkrach.github.io" # the base hostname & protocol for your site
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github_username:  tkrach
# Build settings
markdown: kramdown
