title: Tim Krach
description: Personal website of Tim Krach
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkrach.github.io" # the base hostname & protocol for your site
theme: minima
github_username:  tkrach
# Build settings
markdown: kramdown
